"""
LangGraph State Definition.

The state flows through the graph: Planner -> Researchers -> Critic -> Validator -> Writer.
Each node reads and writes specific fields. TypedDict enables LangGraph's state management.
"""

from typing import TypedDict, Optional


class SubTask(TypedDict):
    """A single research sub-task generated by the Planner."""
    id: str
    description: str
    search_query: str
    dependencies: list[str]


class Finding(TypedDict):
    """A single verified finding from a researcher."""
    task_id: str
    claim: str
    source_url: str
    confidence: str
    validated: bool


class TaskResult(TypedDict):
    """The output of a researcher for a sub-task."""
    task_id: str
    description: str
    findings: list[Finding]
    summary: str
    needs_more_research: bool
    critic_passed: bool
    critic_score: int
    critic_feedback: str
    retry_count: int


class ResearchState(TypedDict):
    """
    The complete state of a research session.

    task_results and findings use replace semantics (no operator.add).
    This prevents duplicate accumulation when the critic triggers retries.
    """
    query: str
    subtasks: list[SubTask]
    task_results: list[TaskResult]
    findings: list[Finding]
    report: str
    current_task: Optional[str]
    all_tasks_complete: bool
    needs_revision: bool
    revision_task_id: Optional[str]
    error: Optional[str]
    session_id: str
    tokens_used: int
    cost_estimate_usd: float
